/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_semux_crypto_Native */

#ifndef _Included_org_semux_crypto_Native
#define _Included_org_semux_crypto_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_semux_crypto_Native
 * Method:    blake2b
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_semux_crypto_Native_blake2b
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_semux_crypto_Native
 * Method:    ed25519_sign
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_semux_crypto_Native_ed25519_1sign
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_semux_crypto_Native
 * Method:    ed25519_verify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_semux_crypto_Native_ed25519_1verify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
